# Generated by Django 6.0.7 on 2026-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general_question', 'General Question'), ('bug_report', 'Bug Report'), ('feature_request', 'Feature Request'), ('accessibility_feedback', 'Accessibility Feedback')], max_length=40)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('subject__in', ['general_question', 'bug_report', 'feature_request', 'accessibility_feedback'])), name='core_contact_subject_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['new', 'read', 'resolved'])), name='core_contact_status_valid'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='core_contact_name_not_blank'), models.CheckConstraint(condition=models.Q(('email__regex', '^\\s*$'), _negated=True), name='core_contact_email_not_blank'), models.CheckConstraint(condition=models.Q(('message__regex', '^\\s*$'), _negated=True), name='core_contact_message_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('platform', models.CharField(default='macOS', max_length=32)),
                ('architecture', models.CharField(default='Apple Silicon', max_length=32)),
                ('download_url', models.URLField(max_length=2048)),
                ('file_size', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-released_at', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='core_one_active_release'), models.CheckConstraint(condition=models.Q(('version__regex', '^\\s*$'), _negated=True), name='core_release_version_not_blank'), models.CheckConstraint(condition=models.Q(('download_url__regex', '^\\s*$'), _negated=True), name='core_release_download_url_not_blank')],
            },
        ),
    ]
